# Generated by Django 5.0.6 on 2024-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_server_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coasters_ridden',
            field=models.JSONField(default=list),
        ),
    ]
