# Generated by Django 5.0.6 on 2024-06-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_server_app', '0002_profile_coasters_ridden'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coaster_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
