# Generated by Django 5.0.6 on 2024-06-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_server_app', '0006_profile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.JSONField(default=['', '', '', '', '', '', '', '', '', '']),
        ),
    ]
