# Generated by Django 5.0.6 on 2024-06-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_server_app', '0007_alter_profile_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Untitled Post')),
                ('poster_name', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('text_content', models.TextField(max_length=1000)),
                ('liked_by', models.ManyToManyField(related_name='unique_users_who_liked_post', to='capstone_server_app.profile')),
                ('likes', models.ManyToManyField(related_name='post_liked_by', to='capstone_server_app.profile')),
                ('posted_by', models.ForeignKey(on_delete=models.SET('Deleted User'), to='capstone_server_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('poster_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='unique_users_who_liked_image', to='capstone_server_app.profile')),
                ('likes', models.ManyToManyField(related_name='image_liked_by', to='capstone_server_app.profile')),
                ('posted_by', models.ForeignKey(on_delete=models.SET('Deleted User'), to='capstone_server_app.profile')),
            ],
        ),
    ]
