# Generated by Django 5.0.6 on 2024-06-14 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_server_app', '0008_forumpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.TextField(default='Untitled Image'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_name', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('text_content', models.TextField(max_length=1000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_server_app.forumpost')),
                ('posted_by', models.ForeignKey(on_delete=models.SET('Deleted User'), to='capstone_server_app.profile')),
            ],
        ),
    ]
