# Generated by Django 5.0.6 on 2024-06-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_server_app', '0009_alter_image_title_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='unique_users_who_liked_post', to='capstone_server_app.profile'),
        ),
    ]
