# Generated by Django 5.0.6 on 2024-06-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_server_app', '0010_alter_forumpost_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileViewState',
            field=models.TextField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('FRIENDS ONLY', 'Friends Only')], default='Public'),
        ),
    ]
