# Generated by Django 5.0.6 on 2024-06-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_server_app', '0013_dataimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataImage',
        ),
    ]
