# Generated by Django 5.0.6 on 2024-06-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_server_app', '0014_delete_dataimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='capstone_server_app.profile'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.TextField(default='Untitled Post', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.TextField(default='Untitled Image', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.TextField(max_length=20),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('founder', models.ForeignKey(on_delete=models.SET('Deleted User'), to='capstone_server_app.profile')),
                ('group_admin', models.ManyToManyField(related_name='group_admin', to='capstone_server_app.profile')),
                ('members', models.ManyToManyField(related_name='members', to='capstone_server_app.profile')),
            ],
        ),
    ]
