# Generated by Django 5.0.6 on 2024-06-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_server_app', '0015_profile_friends_alter_forumpost_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='capstone_server_app.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='capstone_server_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_server_app.group')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_server_app.profile')),
            ],
        ),
    ]
