# Generated by Django 5.0.6 on 2024-06-20 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_server_app', '0016_friendinvite_groupinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_server_app.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_server_app.profile')),
            ],
        ),
    ]
