# Generated by Django 5.0.6 on 2024-06-20 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_server_app', '0017_groupjoinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('text_content', models.TextField(max_length=1000)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_server_app.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone_server_app.profile')),
            ],
        ),
    ]
