# Generated by Django 5.0.6 on 2024-05-15 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0002_alter_customer_name_alter_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='number',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 14, 45, 52, 774928)),
        ),
    ]
