# Generated by Django 5.0.6 on 2024-05-15 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0004_alter_customerorder_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 14, 55, 1, 910133)),
        ),
    ]
