# Generated by Django 5.0.6 on 2024-05-15 19:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0005_alter_customerorder_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 15, 13, 37, 437610)),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycling_store_app.vehicle'),
        ),
    ]
