# Generated by Django 5.0.6 on 2024-05-16 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0009_customer_vehicles_owned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 10, 33, 11, 234486)),
        ),
    ]
