# Generated by Django 5.0.6 on 2024-05-16 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0010_alter_customerorder_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='vehicles_owned',
        ),
        migrations.AddField(
            model_name='customer',
            name='bicycles_owned',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='bmx_bikes_owned',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='mountain_bikes_owned',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='tricycles_owned',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='unicycles_owned',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 10, 49, 49, 130957)),
        ),
    ]
